"""
This type stub file was generated by pyright.
"""

import doctest
from singer import utils
from singer.utils import chunk, load_json, parse_args, ratelimit, should_sync_field, strftime, strptime, update_state
from singer.logger import get_logger, log_critical, log_debug, log_error, log_exception, log_fatal, log_info, log_warning
from singer.metrics import Counter, Timer, http_request_timer, job_timer, record_counter
from singer.messages import ActivateVersionMessage, Message, RecordMessage, SchemaMessage, StateMessage, format_message, parse_message, write_message, write_record, write_records, write_schema, write_state, write_version
from singer.transform import NO_INTEGER_DATETIME_PARSING, Transformer, UNIX_MILLISECONDS_INTEGER_DATETIME_PARSING, UNIX_SECONDS_INTEGER_DATETIME_PARSING, _transform_datetime, resolve_schema_references, transform
from singer.catalog import Catalog, CatalogEntry
from singer.schema import Schema
from singer.bookmarks import clear_bookmark, clear_offset, get_bookmark, get_currently_syncing, get_offset, reset_stream, set_currently_syncing, set_offset, write_bookmark
from singer.exceptions import SingerConfigurationError, SingerDiscoveryError, SingerError, SingerRetryableRequestError, SingerSyncError

if __name__ == "__main__":
    ...
