"""
This type stub file was generated by pyright.
"""

def ensure_bookmark_path(state, path):
    ...

def write_bookmark(state, tap_stream_id, key, val):
    ...

def clear_bookmark(state, tap_stream_id, key):
    ...

def reset_stream(state, tap_stream_id):
    ...

def get_bookmark(state, tap_stream_id, key, default=...):
    ...

def set_offset(state, tap_stream_id, offset_key, offset_value):
    ...

def clear_offset(state, tap_stream_id):
    ...

def get_offset(state, tap_stream_id, default=...):
    ...

def set_currently_syncing(state, tap_stream_id):
    ...

def get_currently_syncing(state, default=...):
    ...

