"""
This type stub file was generated by pyright.
"""

'''Provides an object model for a Singer Catalog.'''
LOGGER = ...
def write_catalog(catalog): # -> None:
    ...

class CatalogEntry:
    def __init__(self, tap_stream_id=..., stream=..., key_properties=..., schema=..., replication_key=..., is_view=..., database=..., table=..., row_count=..., stream_alias=..., metadata=..., replication_method=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def is_selected(self):
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        ...
    


class Catalog:
    def __init__(self, streams) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    @classmethod
    def load(cls, filename): # -> Catalog:
        ...
    
    @classmethod
    def from_dict(cls, data): # -> Catalog:
        ...
    
    def to_dict(self): # -> dict[str, list[Any]]:
        ...
    
    def dump(self): # -> None:
        ...
    
    def get_stream(self, tap_stream_id): # -> None:
        ...
    
    def get_selected_streams(self, state): # -> Generator[Any, Any, None]:
        ...
    


