"""
This type stub file was generated by pyright.
"""

def get_logger(): # -> Logger:
    """Return a Logger instance appropriate for using in a Tap or a Target."""
    ...

def log_debug(msg, *args, **kwargs): # -> None:
    ...

def log_info(msg, *args, **kwargs): # -> None:
    ...

def log_warning(msg, *args, **kwargs): # -> None:
    ...

def log_error(msg, *args, **kwargs): # -> None:
    ...

def log_critical(msg, *args, **kwargs): # -> None:
    ...

def log_fatal(msg, *args, **kwargs): # -> None:
    ...

def log_exception(msg, *args, **kwargs): # -> None:
    ...

