"""
This type stub file was generated by pyright.
"""

def new(): # -> dict[Any, Any]:
    ...

def to_map(raw_metadata): # -> dict[tuple[Any, ...], Any]:
    ...

def to_list(compiled_metadata): # -> list[dict[str, Any]]:
    ...

def delete(compiled_metadata, breadcrumb, k): # -> None:
    ...

def write(compiled_metadata, breadcrumb, k, val):
    ...

def get(compiled_metadata, breadcrumb, k):
    ...

def get_standard_metadata(schema=..., schema_name=..., key_properties=..., valid_replication_keys=..., replication_method=...): # -> list[dict[str, Any]]:
    ...

