"""
This type stub file was generated by pyright.
"""

'''Provides an object model for JSON Schema'''
STANDARD_KEYS = ...
class Schema:
    '''Object model for JSON Schema.

    Tap and Target authors may find this to be more convenient than
    working directly with JSON Schema data structures.

    '''
    def __init__(self, type=..., format=..., properties=..., items=..., selected=..., inclusion=..., description=..., minimum=..., maximum=..., exclusiveMinimum=..., exclusiveMaximum=..., multipleOf=..., maxLength=..., minLength=..., additionalProperties=..., anyOf=..., patternProperties=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        '''Return the raw JSON Schema as a (possibly nested) dict.'''
        ...
    
    @classmethod
    def from_dict(cls, data, **schema_defaults): # -> Schema:
        '''Initialize a Schema object based on the JSON Schema structure.

        :param schema_defaults: The default values to the Schema
        constructor.'''
        ...
    


